stages:
  - deploy

create_manual:
  stage: deploy
  only:
    - schedules
  #image: aergus/latex
  image: ubuntu:latest
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - apt-get install -y make latex
    - latex --version
  script:
    - cd doc/Tex; make PDF
  artifacts:
    paths:
      - ./doc/SWMF.pdf
      - ./doc/SWPC.pdf
      - ./doc/TESTING.pdf
      - ./doc/REFERENCE.pdf
      - ./doc/MAINTENANCE.pdf
      - ./doc/PHYSICS.pdf
      - ./doc/SOFTWARE_STANDARD.pdf