variables:
  GCC_V: 9

stages:
  - deploy

create_manual:
  stage: deploy
  only:
    - schedules
  #image: aergus/latex
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata openmpi-bin libopenmpi-dev
    - apt-get install -y gcc gfortran g++ make
    - apt-get install -y texlive
    - apt-get install -y ghostscript
    - eval $(ssh-agent -s)
    # add private keys
    - echo "$SSH_PRIVATE_KEY_SHARE" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.umich.edu >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "csem@umich.edu"
    - git config --global user.name "GitLab Runner"

  script:
    # Check large files
    - perl -e '$a=`find * -type f -size +6M -exec ls -hl {} \\;`; die "Files exceeding 6M size limit $a\n" if $a; exit 0'
    # Check ssh connection
    - ssh git@gitlab.umich.edu
    # Clone repos
    - ./Config.pl -install -compiler=gfortran
    # Create manual
    - make PDF
    # check that basic things still compile
    - make test8_compile
    - make test9_compile
    - make test_swpc_compile
  artifacts:
    name: manuals
    paths:
      - ./doc/SWMF.pdf
      - ./doc/SWPC.pdf
      - ./doc/TESTING.pdf
      - ./doc/MAINTENANCE.pdf
      - ./doc/PHYSICS.pdf
      - ./doc/SOFTWARE_STANDARD.pdf
    expire_in: 1 day
